[package]
name = "episode_renamer"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.10.0"
once_cell = "1.16.0"
regex = "1.7.0"
terminal_size = "0.2.3"
